services:
  db:
    image: anilkumarnarapali/pyapp:db-image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
     -mynetwork

  auth_service:
    image: anilkumarnaraplli/pyapp:auth-image
    deploy:
     replicas: 1
    ports:
     - "5001:5001"
    networks:
     -mynetwork
    depends_on:
     - db   
  book_service:
   image: anilkumarnarapalli/pyapp:book_image
   deploy:
    replicas: 1
   ports:
    - "5002:5002"
   networks:
    - mynetwork
   depends_on:
    - db
 
  borrow_service:
   image: anilkumarnarapalli/pyapp:borrow_image
   deploy:
    replicas: 1
   ports:
    - "5003:5003"
   networks:
    - mynetwork 
   depends_on:
    - db

  frontend:
   image: anilkumarnarapalli/pyapp:frontend
   deploy:
    replicas:1
   ports:
     - "5000:5000"
   depends_on:
    - auth
    - book
    - borrow

  networks:
  mynetwork:
    driver: overlay
  
